version: '3.8'

services:
  # --- 🗄️ BASE DE DATOS POSTGRESQL ---
  database:
    image: postgres:15-alpine
    container_name: sdb-database
    restart: always
    environment:
      POSTGRES_DB: proyecto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345678910" # 🔑 Forzado explícito con el número 3
    volumes:
      - sdb_db_data:/var/lib/postgresql/data
    networks:
      - sdb-network

  # --- 🧠 SERVICIO BACKEND (Laravel API) ---
  backend:
    build:
      context: ./Sistema-backend
      dockerfile: Dockerfile
    container_name: sdb-backend
    restart: always
    depends_on:
      - database
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: proyecto
      DB_USERNAME: postgres
      DB_PASSWORD: "12345678910" # 🔑 Emparejado exactamente con la base de datos
    networks:
      - sdb-network

  # --- 💻 SERVICIO CLIENTE (Vue 3 + NGINX) ---
  frontend:
    build:
      context: ./Sistema-frontend
      dockerfile: Dockerfile
    container_name: sdb-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - sdb-network

volumes:
  sdb_db_data:

networks:
  sdb-network:
    driver: bridge